name: PyData-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - rise
  - dvc-gs
  - numpy
  - pandas
  - molvs
  - rdkit
  - pubchempy
  - scikit-learn